const prompts = [
  "Write about a person who always makes you laugh. ",
  "What was the best gift you received as a child? ",
  "Write about an event in your life that changed it for the better.",
  "Who has loved you unconditionally? ",
  "What guilty pleasure are you secretly grateful for? ",
  "Write about a person you are grateful for, but sometimes take for granted.",
  "What about today made you smile? ",
  "What did you eat this week that was delicious?",
  "What is something great about your community?",
  "Write about something that always makes you smile, no matter what.",
  "What about your living space are you especially thankful for? ",
  "Write down one good thing that happened to you today.",
  "What in your childhood are you grateful for? ",
  "Who served as a mentor to you (whether they knew it or not)? ",
  "Write about three skills or talents you have that serve you well.",
  "What do you really appreciate about your life?",
  "What has surprised you, in a good way? ",
  "Describe your favorite mundane moment of the day.",
  "What gift have you given that has made a difference in someone’s life? ",
  "Write about a positive interaction you had with a stranger. ",
  "Who or what in your life are you happy to have let go?",
  "List 5 positive qualities of the first person you usually talk to each day.",
  "What was your best day ever? ",
  "List 5 things that spark your curiosity and inspire your interest.",
  "What friend are you most grateful for? What makes them special?",
  "What makes you laugh so hard you get tears in your eyes? ",
  "Where is your “happy place”? Describe it.",
  "What positive impact did you have this week? ",
  "What could you do this week to express gratitude to others? ",
  "What one thing do you own that makes every day a little bit easier?",
  "What character trait are you most grateful for? ",
  "What adversity are you grateful for? ",
  "What are your favorite things in the natural world? ",
  "What about your daily routine are you grateful for?",
  "What do you deeply enjoy doing alone? ",
  "Did a stranger ever do a favor for you?",
  "Write about something you think is adorable. ",
  "What 5 songs are you grateful for? Why? ",
  "Write about what makes your pet so special.",
  "What freedoms are you grateful for? ",
  "How have you grown in the past year?",
  "What book or movie are you grateful for? How did it impact you? ",
  "Write about a favorite memory.",
  "Which day was more special than any other?",
  "What’s the most memorable conversation you’ve had in the past year?",
  "Who helps you achieve your goals? ",
  "List 10 frivolous things that bring you joy.",
  "What could you not live without? ",
  "Write about a random act of kindness.",
  "Who taught you about unconditional love? ",
  "What about your upbringing are you most grateful for?",
  "Who made you feel good this week? ",
];

export default prompts;
